spring:
  cloud:
    gateway:
      server:
        webflux:
          enabled: false
        webmvc:
          routes:
            - id: auth-service-route
              uri: http://localhost:8081
              predicates:
                - Host=auth
server:
  port: 8080
  forward-headers-strategy: framework

jwt:
  secret: <jwt-secret>

cors:
  allowed-origins: http://localhost:80,http://localhost